//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyComponents.wdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wdService.IwithdrawDeposit")]
    public interface IwithdrawDeposit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwithdrawDeposit/deposit", ReplyAction="http://tempuri.org/IwithdrawDeposit/depositResponse")]
        bool deposit(int value, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwithdrawDeposit/deposit", ReplyAction="http://tempuri.org/IwithdrawDeposit/depositResponse")]
        System.Threading.Tasks.Task<bool> depositAsync(int value, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwithdrawDeposit/withdraw", ReplyAction="http://tempuri.org/IwithdrawDeposit/withdrawResponse")]
        bool withdraw(int value, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwithdrawDeposit/withdraw", ReplyAction="http://tempuri.org/IwithdrawDeposit/withdrawResponse")]
        System.Threading.Tasks.Task<bool> withdrawAsync(int value, string user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwithdrawDepositChannel : MyComponents.wdService.IwithdrawDeposit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwithdrawDepositClient : System.ServiceModel.ClientBase<MyComponents.wdService.IwithdrawDeposit>, MyComponents.wdService.IwithdrawDeposit {
        
        public IwithdrawDepositClient() {
        }
        
        public IwithdrawDepositClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwithdrawDepositClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwithdrawDepositClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwithdrawDepositClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool deposit(int value, string user) {
            return base.Channel.deposit(value, user);
        }
        
        public System.Threading.Tasks.Task<bool> depositAsync(int value, string user) {
            return base.Channel.depositAsync(value, user);
        }
        
        public bool withdraw(int value, string user) {
            return base.Channel.withdraw(value, user);
        }
        
        public System.Threading.Tasks.Task<bool> withdrawAsync(int value, string user) {
            return base.Channel.withdrawAsync(value, user);
        }
    }
}
